name: test-with-data
run-name: ${{ github.actor }} is testing commands with sample data
on: 
  push:
jobs:
  check-code-finishes:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python3 -m pip install --upgrade pip pandas
      - run: python3 -m pip install --upgrade pip scikit-learn
      - run: python3 -m pip install --upgrade pip 
      - run: python3 -m pip install --upgrade numpy==1.26.4
      - run: python3 -m pip install --upgrade pip pytest
      - run: curl -L -o data.zip 'https://www.dropbox.com/scl/fo/g7be8yqf6cbx6cexfgd3z/h?rlkey=bp89iq0mab48mwy75kwbliqtc&dl=0?dl=1'
      - run: sudo apt-get install unzip
      - run: unzip data.zip -x / -d data
      - run: python3 -m percolator_RESET --overwrite T --get_psms T --get_all_psms T --initial_dir TailorScore --seed 1 ./data/test1/narrow_50.make-pin.pin ./data/test1/tide-index.peptides.txt
      - run: python3 -m percolator_RESET --overwrite T --pair F --seed 1 ./data/test1/narrow_50.make-pin.pin
      - run: python3 -m percolator_RESET --overwrite T --dynamic_competition F --seed 1 ./data/test1/narrow_50.make-pin.pin
      - run: python3 -m percolator_RESET --seed 0 --score TailorScore --initial_dir TailorScore --FDR_threshold 0.3 --overwrite T ./data/test2/narrow_50_sep.tide-search.target.pin,./data/test2/narrow_51_sep.tide-search.target.pin,./data/test2/narrow_50_sep.tide-search.decoy.pin,./data/test2/narrow_51_sep.tide-search.decoy.pin ./data/test2/tide-index-0.peptides.txt,./data/test2/tide-index-1.peptides.txt
      - run: python3 -m percolator_RESET --seed 0 --FDR_threshold 0.3 --overwrite T  ./data/test2/narrow_50_sep.tide-search.target.pin,./data/test2/narrow_51_sep.tide-search.target.pin,./data/test2/narrow_50_sep.tide-search.decoy.pin,./data/test2/narrow_51_sep.tide-search.decoy.pin ./data/test2/tide-index-0.peptides.txt,./data/test2/tide-index-1.peptides.txt
      - run: python3 -m percolator_RESET --seed 0 --pair F --FDR_threshold 0.3 --overwrite T  ./data/test2/narrow_50_sep.tide-search.target.pin,./data/test2/narrow_51_sep.tide-search.target.pin,./data/test2/narrow_50_sep.tide-search.decoy.pin,./data/test2/narrow_51_sep.tide-search.decoy.pin 
      - run: python3 -m percolator_RESET --seed 0 --reverse T --overwrite T  ./data/test4/comet_open_top50.comet.pin
      - run: python3 -m pytest ./percolator_RESET/tests/