name: test-with-data
run-name: ${{ github.actor }} is testing commands with sample data
on: 
  push:
jobs:
  check-code-finishes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python3 -m pip install --upgrade pip pandas
      - run: python3 -m pip install --upgrade pip scikit-learn
      - run: python3 -m pip install --upgrade pip numpy
      - run: python3 functions/do_FDR_percolator.py --overwrite T --get_psms T --seed 1 ./data/test1/narrow_50.make-pin.pin ./data/test1/tide-index.peptides.txt
      - run: python3 functions/do_FDR_percolator.py --overwrite T --dynamic_competition F --seed 1 ./data/test1/narrow_50.make-pin.pin